### ISSUE TITLE
RDT actuator

### ISSUE THREAD

**Issue by BonjourGit** [intel/intent-driven-orchestration#5]
Hi,

Could you please elaborate on what the terminology "RDT" stands for, and possibly a bit more information about it?

Many thanks!

**Comment by tmetsch** [comment]
Hi,

RDT stands for Resource Director Technology; you can find more information over here [here](https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html).

Cheers!

**Comment by BonjourGit** [comment]
Hi @tmetsch,

Thank you for the reply! A further question is that does the intent-driven-orchestration implementation depend on Intel RDT tech?

Thanks!

**Comment by tmetsch** [comment]
Good question, so it is independent of it; If your platform supports it the planner can eventually make use of it. If your platform does not support it, the planner will not consider it either. On top of that, you can individually decide which actuators you want to have active in your system.

Hope that helps.

**Comment by BonjourGit** [comment]
Thank you for the help. Appreciated.
